### ISSUE TITLE
Are apostrophes allowed?

### ISSUE THREAD

**Issue by charchalis** [joaosilvalopes/word-dice#6]
https://github.com/joaosilvalopes/word-dice/blob/8b325cd017c0788bb8307da761f9910b01f72e04/data/it-IT#L281

**Comment by joaosilvalopes** [comment]
https://lifeinitaly.com/accents-and-apostrophes/

In Italian an apostrophe is an elision which occurs when a word that ends with a vowel and a word that begins with a vowel are used together in a sentence.

As the apostrophe in italian is essentially separating two words (and we only want one word outputs) i would say no.
